shops:
  Blocks:
    white_wool:
      slot: 11
      material: WHITE_WOOL
      amount: 16
      cost: 1
      display_name: "White Wool"
      description:
        - "&7Just the usual!"
    light_gray_wool:
      slot: 12
      material: LIGHT_GRAY_WOOL
      amount: 16
      cost: 2
      display_name: "Light Gray Wool"
      description:
        - "&7Can't turn to dust!"
    obsidian:
      slot: 13
      material: OBSIDIAN
      amount: 1
      cost: 50
      display_name: "Obsidian"
      description:
        - "&7The strongest!"
    oak_planks:
      slot: 20
      material: OAK_PLANKS
      amount: 16
      cost: 5
      display_name: "Oak Plank"
      description:
        - "&7Regular wood!"
    stone_bricks:
      slot: 21
      material: STONE_BRICKS
      amount: 16
      cost: 10
      display_name: "Stone Bricks"
      description:
        - "&7Regular stone!"
    deepslate_bricks:
      slot: 22
      material: DEEPSLATE_BRICKS
      amount: 16
      cost: 16
      display_name: "Deepslate Bricks"
      description:
        - "&7Stronger than stone!"
    polished_deepslate:
      slot: 23
      material: POLISHED_DEEPSLATE
      amount: 16
      cost: 32
      display_name: "Polished Deepslate"
      description:
        - "&7Immune to TNT!"
    oak_slab:
      slot: 29
      material: OAK_SLAB
      amount: 8
      cost: 5
      display_name: "Oak Slab"
      description:
        - "&7Half a plank!"
    stone_brick_slab:
      slot: 30
      material: STONE_BRICK_SLAB
      amount: 8
      cost: 10
      display_name: "Stone Brick Slab"
      description:
        - "&7Half a stone brick!"
    deepslate_brick_slab:
      slot: 31
      material: DEEPSLATE_BRICK_SLAB
      amount: 8
      cost: 16
      display_name: "Deepslate Brick Slab"
      description:
        - "&7Stronger than stone slabs!"
    polished_deepslate_slab:
      slot: 32
      material: POLISHED_DEEPSLATE_SLAB
      amount: 8
      cost: 32
      display_name: "Polished Deepslate Slab"
      description:
        - "&7Immune to TNT!"
  Consumables:
    regen_apple:
      slot: 11
      material: APPLE
      amount: 1
      cost: 5
      display_name: "Regen Apple"
      description:
        - "&7Gives regeneration I for"
        - "&730 seconds once consumed!"
  Utility:
    dusty:
      slot: 11
      material: SUGAR
      amount: 1
      cost: 15
      display_name: "Dusty"
      description:
        - "&7Blocks in 10 block radius"
        - "&7get turned into dust!"
    explosive:
      slot: 12
      material: TNT
      amount: 1
      cost: 30
      display_name: "Explosive"
      description:
        - "&7Goes KABOOM!"
    rockets:
      slot: 13
      material: FIREWORK_ROCKET
      amount: 1
      cost: 40
      display_name: "Rocket"
      description:
        - "&7Makes you fly!"