name: ElytraPVP
version: '${project.version}'
main: me.roustytousty.elytrapvp.ElytraPVP
api-version: '1.21'

dependencies:
  server:
    DecentHolograms:
      load: BEFORE
      required: true



commands:

  test:
    description: "Test command for Rousty!"
    permission: op
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"

  # Gui commands
  upgrademenu:
    aliases: [upgrade]
    description: "Opens the upgrade GUI"
  shopmenu:
    aliases: [shop]
    description: "Opens the shop GUI"
  statsmenu:
    aliases: [leaderboards, lb]
    description: "Opens the stats GUI"
  perksmenu:
    aliases: [perks]
    description: "Opens the perks GUI"
  eventsmenu:
    aliases: [events]
    description: "Opens the events GUI"
  rebirthmenu:
    aliases: [rebirth]
    description: "Opens the rebirth GUI"
  cosmeticmenu:
    aliases: [cosmetics]
    description: "Opens the cosmetic GUI"
  questmenu:
    aliases: [quests]
    description: "Opens the quest GUI"

  # Player commands
  gold:
    aliases: [money, bal, balance]
    description: "Check how much gold you have!"
  stats:
    description: "Opens specific players stats!"
  discord:
    aliases: [dc]
    description: "Sends an invite link to discord!"
  spawn:
    aliases: [hub, lobby, s]
    description: "Teleports you to spawn!"
  ip:
    aliases: [serverip]
    description: "Provides the server IP!"
  link:
    aliases: [freerank]
    description: "Initiates linking between minecraft and discord!"
  unlink:
    description: "Initiates unlinking between minecraft and discord!"
  afk:
    description: "Initiates afk status and rewards!"
  rules:
    description: "Displays all in-game rules!"

  # Staff commands
  reloadupgradeconfig:
    description: "Reloads the upgrade config!"
    permission: op
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  reloadshopconfig:
    description: "Reloads the shop config!"
    permission: op
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  reloadregionconfig:
    description: "Reloads the region config!"
    permission: op
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  buildmode:
    description: "Toggles buildmode!"
    permission: op
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  feed:
    description: "Feeds you!"
    permission: op
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  setgold:
    description: "Set players gold amount!"
    permission: op
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  addgold:
    description: "Add gold to players gold amount!"
    permission: op
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  setshards:
    description: "Set players shards amount!"
    permission: op
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  addshards:
    description: "Add shards to players shards amount!"
    permission: op
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  setkitlevel:
    description: "Set players kit level!"
    permission: op
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  eventactivate:
    description: "Activates a specific event!"
    permission: op
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  mapregionreset:
    description: "Resets the map!"
    permission: op
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  maptimerreset:
    description: "Resets the map reset timer!"
    permission: op
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"

  kick:
    description: "Kicks a player!"
    permission: group.guide
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  ban:
    description: "Bans a player!"
    permission: group.guide
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  unban:
    description: "Unbans a player!"
    permission: group.guide
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  mute:
    description: "Mutes a player!"
    permission: group.guide
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  unmute:
    description: "Unmutes a player!"
    permission: group.guide
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  punishmenthistory:
    description: "Shows player's punishment history!"
    permission: group.guide
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  clearchat:
    description: "Clears the chat!"
    permission: group.guide
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  mutechat:
    description: "Mutes the chat!"
    permission: group.guide
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"
  unmutechat:
    description: "Unmutes the chat!"
    permission: group.guide
    permission-message: "&c&lEcoWings &8| &fYou don't have permission to use this command!"