name: ElytraPVP
version: '${project.version}'
main: me.roustytousty.elytrapvp.ElytraPVP
api-version: '1.21'

dependencies:
  server:
    DecentHolograms:
      load: BEFORE
      required: true



commands:

  test:
    description: "Test command for Rousty!"

  # Gui commands
  upgrademenu:
    description: "Opens the upgrade GUI"
  shopmenu:
    description: "Opens the shop GUI"
  statsmenu:
    description: "Opens the stats GUI"
  perksmenu:
    description: "Opens the perks GUI"
  eventsmenu:
    description: "Opens the events GUI"
  rebirthmenu:
    description: "Opens the rebirth GUI"

  # Player commands
  gold:
    aliases: [money, bal, balance]
    description: "Check how much gold you have"
  stats:
    description: "Opens specific players stats"
  discord:
    description: "Sends an invite link to discord"

  # Staff commands
  reloadcache:
    description: "Reloads the player data cache!"
    permission: op
    permission-message: "&c&lWwwings &8| &fYou don't have permission to use this command!"
  reloadupgradeconfig:
    description: "Reloads the upgrade config!"
    permission: op
    permission-message: "&c&lWwwings &8| &fYou don't have permission to use this command!"
  buildmode:
    description: "Toggles buildmode!"
    permission: op
    permission-message: "&c&lWwwings &8| &fYou don't have permission to use this command!"
  feed:
    description: "Feeds you!"
    permission: op
    permission-message: "&c&lWwwings &8| &fYou don't have permission to use this command!"
  setgold:
    description: "Set players gold amount!"
    permission: op
    permission-message: "&c&lWwwings &8| &fYou don't have permission to use this command!"
  eventactivate:
    description: "Activates a specific event!"
    permission: op
    permission-message: "&c&lWwwings &8| &fYou don't have permission to use this command!"